sharedeviceplugin:
  image:
    repository: cnrancher/gpu-device-plugin
    tag: "v0.1.2"
defaultScheduler:
  version: "v1.24"
  supportedVersions:
    v1.18:
      repository: "rancher/hyperkube"
      tag: "v1.18.20-rancher1"
    v1.19:
      repository: "rancher/hyperkube"
      tag: "v1.19.16-rancher2"
    v1.20:
      repository: "rancher/hyperkube"
      tag: "v1.20.15-rancher2"
    v1.21:
      repository: "rancher/hyperkube"
      tag: "v1.21.14-rancher1"
    v1.22:
      repository: "rancher/hyperkube"
      tag: "v1.22.17-rancher1"
    v1.23:
      repository: "rancher/hyperkube"
      tag: "v1.23.16-rancher2"
    v1.24:
      repository: "rancher/hyperkube"
      tag: "v1.24.10-rancher4"
schedulerextender:
  image:
    repository: cnrancher/gpu-scheduler-extender
    tag: "v0.1.2"
  schedulerName: rancher-gpushare-scheduler
  port: 9100
  verbose: 4
  nodeSelector: {}
  tolerations: []
  affinity: {}
# GPU Sharing Memory unit: GiB or MiB    
memoryunit: GiB
global:
  systemDefaultRegistry: ""

runtimeClassName: null
