apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
  labels:
    app: webhook-receiver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
      - name: webhook-receiver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - /webhook-receiver
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /state
            port: {{ .Values.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
        ports:
        - containerPort: 9094
        volumeMounts:
        - name: config
          mountPath: /etc/webhook-receiver
{{- if .Values.affinity }}
        affinity:
{{ toYaml .Values.affinity | indent 10 }}
{{- end }}
{{- if .Values.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.nodeSelector | indent 10 }}
{{- end }}
{{- if .Values.tolerations }}
        tolerations:
{{ toYaml .Values.tolerations | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: config
        secret:
          secretName: webhook-receiver
