annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.28.0-0'
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.9.0-0'
  catalog.cattle.io/release-name: rancher-cce-operator-crd
apiVersion: v2
appVersion: 0.4.2
description: CCE Operator CustomResourceDefinitions
name: rancher-cce-operator-crd
version: 103.0.1+up0.4.2
