iface: ""

podCIDR: "10.42.0.0/16"

arpPolicy: "arping"

proxyARP: false

clusterType: "Default"

multus:
  cniVersion: "0.3.1"

ncResources:
  limits:
    memory: 512Mi
nadcResources:
  limits:
    memory: 512Mi

image:
  multus:
    repository: cnrancher/hardened-multus-cni
    tag: v3.9.3-rancher2
  networkController:
    repository: cnrancher/network-controller
    tag: v0.8.2
  admission:
    repository: cnrancher/network-admission-deploy
    tag: v0.8.2
  nadController:
    repository: cnrancher/k8s-net-attach-def-controller
    tag: v0.3.4
  staticMacvlan:
    repository: cnrancher/static-macvlan-cni
    tag: v0.5.4

global:
  cattle:
    systemDefaultRegistry: ""

privateRegistry:
  registryUrl: ~
