apiVersion: v1
kind: Service
metadata:
  name: expose-grafana-metrics
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{ .Values.apiGroup }}: "true"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 3000
      targetPort: web