{{ if eq .Values.sinktarget "webhook"}}
{{ if .Values.sink.webhook.use_custom_body }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sink.webhook.custom_body_configmap_name }}
  namespace: {{ .Release.Namespace }}
data:
  content: ""
{{ end }}
{{ end }}
