---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpushare-device-plugin
spec:
  selector:
    matchLabels:
      component: gpushare-device-plugin
      app: gpushare
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: gpushare-device-plugin
        app: gpushare
    spec:
      serviceAccount: gpushare-device-plugin
      hostNetwork: true
      nodeSelector:
        gpu.cattle.io/type: "share"
      containers:
      - image: "{{ .Values.image.sharedeviceplugin.repository }}:{{ .Values.image.sharedeviceplugin.tag }}"
        name: gpushare-device-plugin
        # Make this pod as Guaranteed pod which will never be evicted because of node's resource consumption.
        command:
          - gpu-device-plugin
          - -logtostderr
          - --v=5
          - --memory-unit={{ .Values.memoryunit }}
        resources:
          limits:
            memory: "300Mi"
            cpu: "1"
          requests:
            memory: "300Mi"
            cpu: "1"
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/kubelet.conf
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
