apiVersion: v1
kind: Service
metadata:
  name: gpushare-schd-extender
  labels:
    app: gpushare
    component: gpushare-schd-extender
spec:
  type: NodePort
  ports:
  - port: {{ .Values.schedulerextender.ports.targetport }}
    name: http
    targetPort: {{ .Values.schedulerextender.ports.targetport }}
    nodePort: {{ .Values.schedulerextender.ports.nodeport }}
  selector:
    app: gpushare
    component: gpushare-schd-extender
