FROM registry.suse.com/bci/golang:1.19

RUN mkdir -p /dapper
ENV DAPPER_SOURCE /dapper
WORKDIR ${DAPPER_SOURCE}

# Install dependencies.
RUN zypper -n install make wget curl tar patch && zypper clean

# Validation.
CMD make pull-scripts && make validate
