apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installeroperator.qfusion.woqutech.com
spec:
  conversion:
    strategy: None
  group: qfusion.woqutech.com
  names:
    kind: InstallerOperator
    listKind: InstallerOperatorList
    plural: installeroperator
    shortNames:
    - qfi
    singular: installeroperator
  version: v1alpha1
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true