apiVersion: v1
kind: Service
metadata:
  name: access-dashboard
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: ui
