iface: ""

podCIDR: "10.42.0.0/16"

arpPolicy: "arping"

proxyARP: false

clusterType: "Default"

multus:
  cniVersion: "0.3.1"

ncResources:
  limits:
    memory: 512Mi
nadcResources:
  limits:
    memory: 512Mi

image:
  networkController:
    tag: v0.8.0-rc2
  nadController:
    tag: v0.3.0
  staticMacvlan:
    tag: v0.5.0-rc1

global:
  cattle:
    systemDefaultRegistry: ""

privateRegistry:
  registryUrl: ~
