sharedeviceplugin:
  image:
    repository: cnrancher/gpu-device-plugin
    tag: "v0.1.3"
defaultScheduler:
  version: "v1.27"
  supportedVersions:
    v1.23:
      repository: "rancher/hyperkube"
      tag: "v1.23.16-rancher2"
    v1.24:
      repository: "rancher/hyperkube"
      tag: "v1.24.10-rancher4"
    v1.25:
      repository: "rancher/hyperkube"
      tag: "v1.25.6-rancher4"
    v1.26:
      repository: "rancher/hyperkube"
      tag: "v1.26.4-rancher2"
    v1.27:
      repository: "rancher/hyperkube"
      tag: "v1.27.6-rancher1"
schedulerextender:
  image:
    repository: cnrancher/gpu-scheduler-extender
    tag: "v0.1.3"
  schedulerName: rancher-gpushare-scheduler
  port: 9100
  verbose: 4
  nodeSelector: {}
  tolerations: []
  affinity: {}
# GPU Sharing Memory unit: GiB or MiB    
memoryunit: GiB
global:
  systemDefaultRegistry: ""

runtimeClassName: null
