apiVersion: v1
kind: Service
metadata:
  name: orion-controller-nodeport
spec:
  type: NodePort
  selector:
    app: orion
    name: {{ .Values.controller.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.controller.port | atoi }}
    targetPort: {{ .Values.controller.portName2 }}
    nodePort: {{ .Values.controller.nodeport }}
    name: {{ .Values.controller.portName2 }}