apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: orion-scheduler
    algorithmSource:
      policy:
        configMap:
          namespace: {{ .Release.Namespace }}
          name: orion-scheduler-policy
    leaderElection:
      leaderElect: true
      lockObjectName: orion-scheduler
      lockObjectNamespace: {{ .Release.Namespace }}