{{- if semverCompare ">=1.14" .Capabilities.KubeVersion.GitVersion -}}
{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role
  labels:
    app: {{ include "xsky.name" . }}
    chart: {{ include "xsky.chart" . }}
    component: {{ .Values.resizer.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: csi-resizer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: external-resizer-runner
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}