{{- if .Values.drivers.nvidia.enabled }}
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: hami-core-gpu.project-hami.io
spec:
  selectors:
  - cel:
      expression: |-
        device.driver == "hami-core-gpu.project-hami.io" && device.attributes["hami-core-gpu.project-hami.io"].type == "hami-gpu"
{{- end }}
{{- if and .Values.drivers.nvidia.enabled .Values.drivers.fake.enabled }}
---
{{- end }}
{{- if .Values.drivers.fake.enabled }}
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: {{ .Values.drivers.fake.deviceClassName }}
spec:
  selectors:
  - cel:
      expression: |-
        device.driver == "{{ .Values.drivers.fake.driverName }}" && device.attributes["{{ .Values.drivers.fake.driverName }}"].type == "hami-gpu"
{{- end }}