{{- if .Values.drivers.fake.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fake-driver
  namespace: {{ .Release.Namespace }}
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: fake-driver
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fake-driver
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: fake-driver
    spec:
      {{- include "hami.dra.driver.fake.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: hami-dra-driver-service-account
      nodeSelector:
{{ toYaml .Values.drivers.fake.nodeSelector | nindent 8 }}
      tolerations:
{{ toYaml .Values.drivers.fake.tolerations | nindent 8 }}
      affinity:
{{ toYaml .Values.drivers.fake.affinity | nindent 8 }}
      containers:
      - name: fake-driver
        image: {{ include "hami.dra.driver.fake.image" . }}
        imagePullPolicy: {{ .Values.drivers.fake.image.pullPolicy | default "IfNotPresent" }}
        securityContext:
          runAsUser: 0
        command:
        - /bin/fake-driver
        args:
        - --node-name=$(NODE_NAME)
        - --driver-name={{ .Values.drivers.fake.driverName }}
        - --configmap-name={{ include "hami.dra.driver.fake.configMapName" . }}
        - --configmap-namespace={{ .Release.Namespace }}
        - --configmap-key={{ .Values.drivers.fake.configMap.key }}
        - --kubelet-registrar-directory-path={{ .Values.drivers.fake.plugin.kubeletRegistrarDirectoryPath }}
        - --kubelet-plugins-directory-path={{ .Values.drivers.fake.plugin.kubeletPluginsDirectoryPath }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        resources:
{{ toYaml .Values.drivers.fake.resources | nindent 10 }}
        volumeMounts:
        - name: plugins-registry
          mountPath: {{ .Values.drivers.fake.plugin.kubeletRegistrarDirectoryPath }}
        - name: plugins
          mountPath: {{ .Values.drivers.fake.plugin.kubeletPluginsDirectoryPath }}
      volumes:
      - name: plugins-registry
        hostPath:
          path: {{ .Values.drivers.fake.plugin.kubeletRegistrarDirectoryPath }}
          type: DirectoryOrCreate
      - name: plugins
        hostPath:
          path: {{ .Values.drivers.fake.plugin.kubeletPluginsDirectoryPath }}
          type: DirectoryOrCreate
{{- end }}
