{{- if and .Values.drivers.fake.enabled (not .Values.drivers.fake.configMap.existingName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hami.dra.driver.fake.configMapName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.drivers.fake.configMap.key }}: |
{{- if .Values.drivers.fake.configMap.inlineData }}
{{ .Values.drivers.fake.configMap.inlineData | nindent 4 }}
{{- else }}
{{ include "hami.dra.driver.fake.defaultConfig" . | nindent 4 }}
{{- end }}
{{- end }}
