apiVersion: v1
kind: Service
metadata:
  name: alerting-drivers
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
