{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "nginx-ingress.name" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
{{- if .Values.controller.reportIngressStatus.enableLeaderElection }}
  - update
  - create
{{- end }}
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
{{- if .Values.controller.reportIngressStatus.enable }}
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
{{- end }}
{{- if .Values.controller.enableCustomResources }}
- apiGroups:
  - k8s.nginx.org
  resources:
  - virtualservers
  - virtualserverroutes
  - transportservers
  verbs:
  - list
  - watch
  - get
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "nginx-ingress.name" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "nginx-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "nginx-ingress.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
