{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
  labels:
    app: {{ include "xsky.name" . }}
    chart: {{ include "xsky.chart" . }}
    component: {{ .Values.attacher.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: csi-attacher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: external-attacher-runner
  apiGroup: rbac.authorization.k8s.io
{{- end -}}