{{- if semverCompare ">=1.13" .Capabilities.KubeVersion.GitVersion -}}
{{- if .Values.serviceAccounts.snapshotter.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-snapshotter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "xsky.name" . }}
    chart: {{ include "xsky.chart" . }}
    component: {{ .Values.snapshotter.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
{{- end -}}