annotations:
  catalog.cattle.io/kube-version: '>= 1.20.0-0'
  catalog.cattle.io/rancher-version: '>= 2.7.0-0'
apiVersion: v2
appVersion: 2.0.9
description: collect k8s auditlog for rancher auditlog server
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
kubeVersion: '>= 1.20.0-0'
name: rancher-k8s-auditlog-collector
type: application
version: 0.0.2
