apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-{{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: query
spec:
  replicas: {{ .Values.query.replicaCount }}
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      component: query
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        component: query
    spec:
      containers:
        - name: thanos
          image: "{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - query
          {{- if .Values.tls.enabled }}
          - --grpc-client-tls-key
          - /etc/tls/grpc/tls.key
          - --grpc-client-tls-cert
          - /etc/tls/grpc/tls.cert
          - --grpc-client-tls-ca
          - /etc/tls/grpc/tls.ca
          - --grpc-client-tls-secure
          - --grpc-client-server-name
          - {{ .Values.tls.serverName }}   
          {{- end }}
          {{- range .Values.query.stores }}
          - --store={{ . }}
          {{- end }}
          {{- if .Values.store.enabled }}
          - --store
          - thanos-store-{{ .Release.Name }}:10901
          {{- end }}
        {{- range .Values.query.extraArgs }}
          - {{ . }}
        {{- end }}
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.query.resources | nindent 12 }}
          {{- if .Values.tls.enabled }}  
          volumeMounts:
          - mountPath: /etc/tls/grpc
            name: thanos-sidecar-tls
          {{- end }}
        - name: nginx
          image: "{{ template "system_default_registry" . }}{{ .Values.query.proxy.repository }}:{{ .Values.query.proxy.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.query.proxy.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-config
            subPath: default.conf
          {{- if .Values.query.proxy.privateCa }}
          - mountPath: /etc/kubernetes/ssl/certs
            name: ca-cert
          {{- end }}
      nodeSelector:
      {{- include "linux-node-selector" . | nindent 8 }}
      {{- with .Values.query.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.query.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- include "linux-node-tolerations" . | nindent 8 }}
      {{- with .Values.query.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          items:
          - key: default.conf
            path: default.conf
          name: proxy-{{ .Release.Name }}
        name: nginx-config
      {{- if .Values.query.proxy.privateCa }}
      - name: ca-cert
        hostPath:
          path: /etc/kubernetes/ssl/certs
      {{- end }}
      {{- if .Values.tls.enabled }}
      - name: thanos-sidecar-tls
        secret:
          defaultMode: 420
          secretName: thanos-sidecar-tls
      {{- end }}
