{{- if .Values.store.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-{{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: store
spec:
  type: ClusterIP
  ports:
    - port: 10901
      targetPort: 10901
      protocol: TCP
      name: grpc
  selector:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: store
{{- end }}