{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-sidecar-tls
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  tls.ca: {{ .Values.tls.ca }}
  tls.cert: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
{{- end }} 
