apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query-stores
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  thanos-store.yml: |-
    - targets:
      {{- range .Values.query.stores }}
      - {{ . }}
      {{- end }}
      {{- if .Values.store.enabled }}
      - thanos-store-{{ .Release.Name }}:10901
      {{- end }}
