apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-dcgm-exporter
  namespace: cattle-prometheus
spec:
  selector:
    matchLabels:
      app: gpu-dcgm-exporter
  template:
    metadata:
      labels:
        app: gpu-dcgm-exporter
      name: gpu-dcgm-exporter
    spec:
      nodeSelector:
        gpumonitoring.cattle.io: "true"
      containers:
      - image: "{{ .Values.image.nodeexporter.repository }}:{{ .Values.image.nodeexporter.tag }}"
        name: node-exporter
        args:
        - "--web.listen-address=0.0.0.0:{{ .Values.ports.metrics.port }}"
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        - "--collector.textfile.directory=/run/prometheus"
        - "--no-collector.arp"
        - "--no-collector.bcache"
        - "--no-collector.bonding"
        - "--no-collector.conntrack"
        - "--no-collector.cpu"
        - "--no-collector.diskstats"
        - "--no-collector.edac"
        - "--no-collector.entropy"
        - "--no-collector.filefd"
        - "--no-collector.filesystem"
        - "--no-collector.hwmon"
        - "--no-collector.infiniband"
        - "--no-collector.ipvs"
        - "--no-collector.loadavg"
        - "--no-collector.mdadm"
        - "--no-collector.meminfo"
        - "--no-collector.netdev"
        - "--no-collector.netstat"
        - "--no-collector.nfs"
        - "--no-collector.nfsd"
        - "--no-collector.sockstat"
        - "--no-collector.stat"
        - "--no-collector.time"
        - "--no-collector.timex"
        - "--no-collector.uname"
        - "--no-collector.vmstat"
        - "--no-collector.wifi"
        - "--no-collector.xfs"
        - "--no-collector.zfs"
        ports:
        - name: metrics
          containerPort: {{ .Values.ports.metrics.port }}
          hostPort: {{ .Values.ports.metrics.port }}
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
        - name: collector-textfiles
          readOnly: true
          mountPath: /run/prometheus
      - image: "{{ .Values.image.dcgmexporter.repository }}:{{ .Values.image.dcgmexporter.tag }}"
        name: nvidia-dcgm-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: collector-textfiles
          mountPath: /run/prometheus

      hostNetwork: true
      hostPID: true

      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: collector-textfiles
        emptyDir:
          medium: Memory
