{{- if .Values.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcgm-exporter.fullname" . }}
  namespace: {{ include "dcgm-exporter.namespace" . }}
  labels:
    {{- include "dcgm-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcgm-exporter"
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "metrics"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    {{- include "dcgm-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
