annotations:
  catalog.cattle.io/kube-version: '>= 1.20.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/rancher-version: '>= 2.6.0-0'
  catalog.cattle.io/release-name: rancher-blackbox-exporter
  catalog.cattle.io/type: cluster-tool
apiVersion: v2
description: Blackbox Exporter for Prometheus
keywords:
- prometheus
name: rancher-blackbox-exporter
version: 0.0.1
