apiVersion: v1
name: fluent-bit
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
keywords:
  - logging
  - fluent-bit
version: 0.0.1
appVersion: 1.6.8
icon: https://fluentbit.io/assets/img/logo1-default.png
sources:
  - https://github.com/fluent/fluent-bit/
