apiVersion: v1
kind: Service
metadata:
  name: alertmanager-receiver
spec:
  selector:
    app: alertmanager-receiver
  ports:
    - protocol: TCP
      port: {{ .Values.Port }}
      targetPort: 9094