{{- if .Values.monitor.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hami.dra.monitor.fullname" . }}
rules:
- apiGroups: ["resource.k8s.io"]
  resources: ["resourceslices", "resourceclaims"]
  verbs: ["get", "list", "watch"]
{{- end }}

