apiVersion: v2
appVersion: 0.20.2
description: Submariner enables direct networking between Pods and Services in different
  Kubernetes clusters
home: https://submariner-io.github.io/
maintainers:
- email: submariner-dev@googlegroups.com
  name: Contributors to the Submariner project
  url: https://submariner.io/
name: submariner-operator
sources:
- https://submariner-io.github.io/submariner-charts/charts
version: 0.0.1
