apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: blackbox-exporter
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter/
{{- if .Values.affinity }}
        affinity:
{{ toYaml .Values.affinity | indent 10 }}
{{- end }}
{{- if .Values.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.nodeSelector | indent 10 }}
{{- end }}
{{- if .Values.tolerations }}
        tolerations:
{{ toYaml .Values.tolerations | indent 10 }}
{{- end }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
      volumes:
      - name: config
        configMap:
          name: blackbox-exporter
          defaultMode: 420
