annotations:
  catalog.cattle.io/display-name: Multi-cluster Service Addon
  catalog.cattle.io/kube-version: '>= 1.23.0-0'
  catalog.cattle.io/namespace: mcs-addon-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
  catalog.cattle.io/rancher-version: '>= 2.13.0-0 < 2.14.0-0'
  catalog.cattle.io/ui-component: mcs-ext-chart
apiVersion: v2
appVersion: 0.0.1
description: Multi-cluster Service Extension Chart
icon: https://pub-68160d88f4744423960a290fc7a5031d.r2.dev/mcs-icon.png
name: mcs-ext-chart
version: 0.0.1
