enabled: false
image:
  repository: "cnrancher/webhook-receiver"
  tag: v0.2.7-ent2
replicas: 1 
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: {}
affinity: {} 
port: 9094

global:
  systemDefaultRegistry: ""