---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpushare-scheduler-cluster-admin
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: gpushare-extender
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpushare-extender
