image:
  nvidiadeviceplugin:
    repository: cnrancher/k8s-device-plugin
    tag: "v0.10.0"
  sharedeviceplugin:
    repository: cnrancher/gpu-device-plugin
    tag: "v0.1.2"
  schedulerextender:
    repository: cnrancher/gpu-scheduler-extender
    tag: "v0.1.2"
  defaultScheduler:
    version: v1.24
    supportedVersions:
      v1.18: "rancher/hyperkube:v1.18.12-rancher1"
      v1.19: "rancher/hyperkube:v1.19.16-rancher1"
      v1.20: "rancher/hyperkube:v1.20.13-rancher1"
      v1.21: "rancher/hyperkube:v1.21.8-rancher1"
      v1.22: "rancher/hyperkube:v1.21.8-rancher1"
      v1.23: "rancher/hyperkube:v1.21.8-rancher1"
      v1.24: "rancher/hyperkube:v1.21.8-rancher1"
schedulerextender:
  schedulerName: rancher-gpushare-scheduler
  port: 9100
  verbose: 4
  nodeSelector: {}
  tolerations: []
  affinity: {}
# GPU Sharing Memory unit: GiB or MiB    
memoryunit: GiB
global:
  systemDefaultRegistry: ""
