noTimestamp: null
sleepInterval: null

nameOverride: ""
fullnameOverride: ""
selectorLabelsOverride: {}

imagePullSecrets: []
image:
  repository: cnrancher/gpu-feature-discovery
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.6.1"

podAnnotations: {}
podSecurityContext: {}
securityContext:
  privileged: true

resources: {}
nodeSelector:
  feature.node.kubernetes.io/pci-10de.present: "true" # NVIDIA vendor ID
