kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tke-operator
  namespace: cattle-system
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list', 'create', 'watch']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'list', 'create','update', 'watch']
  - apiGroups: ['tke.pandaria.io']
    resources: ['tkeclusterconfigs']
    verbs: ['get', 'list', 'update', 'watch']
  - apiGroups: ['tke.pandaria.io']
    resources: ['tkeclusterconfigs/status']
    verbs: ['update']
