plugin: "Attaching Macvlan"

iface: ""

podCIDR: "10.42.0.0/16"

arpPolicy: "arping"

proxyARP: false

clusterType: "Default"

multus:
  cniVersion: "0.3.1"

canal:
  vethmtu: "0"

ncResources:
  limits:
    memory: 512Mi
nadcResources:
  limits:
    memory: 512Mi

image:
  networkController:
    tag: v0.7.4-rc4
  nadController:
    tag: v0.2.3
  staticMacvlan:
    tag: v0.4.2

global:
  cattle:
    systemDefaultRegistry: ""

privateRegistry:
  registryUrl: ~
