apiVersion: v1
description: Provides gpu management for Rancher2.x
engine: gotpl
maintainers:
- name: jianghang8421
  email: hang.jiang@rancher.com
name: rancher-gpu-management
sources:
- https://github.com/cnrancher
version: 0.0.4
appVersion: "0.1.0"
home: https://github.com/cnrancher
keywords:
- sharing
- management
- gpu
icon: https://raw.githubusercontent.com/jianghang8421/gpu-device-plugin-charts/master/nvidia_logo.png
