{{ if and (not .Values.controller.wildcardTLS.secret) (and .Values.controller.wildcardTLS.cert .Values.controller.wildcardTLS.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-ingress.wildcardTLSName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.controller.wildcardTLS.cert }}
  tls.key: {{ .Values.controller.wildcardTLS.key }}
{{- end }}
