{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
{{- if .Values.controller.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.controller.serviceAccount.imagePullSecrets }}
{{- end }}
{{- end }}
