apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-{{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  default.conf: |-
    # Obtain best http host
    map $http_host $this_host {
            default          $http_host;
            ''               $host;
    }
    map $http_x_forwarded_host $best_http_host {
            default          $http_x_forwarded_host;
            ''               $this_host;
    }

    server {
        listen       8081;

        location / {
            proxy_pass http://localhost:10902/;
            sub_filter_types    text/html application/javascript;
              sub_filter_once     off;
              sub_filter          'var PATH_PREFIX = "";' 'var PATH_PREFIX = ".";';
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }