#!/bin/sh

# Get the folder of Aliyun OSS bucket from Git branch name.
# e.g. branch name: `dev/v2.6` -> folder name: `dev-v2.6`, branch: `release/v2.6` -> folder: `release-v2.6`
if [[ -z "${DRONE_COMMIT_BRANCH}" ]]; then
    echo "ERROR: this script needs to run in drone pipeline."
    exit 1
else
    echo "---- DRONE_COMMIT_BRANCH: ${DRONE_COMMIT_BRANCH}"
    echo "---- Checking git branch format"
    if echo "${DRONE_COMMIT_BRANCH}" | grep "dev/\|release/"; then
        echo "---- Git branch format valid."
    else
        echo "---- Invalid git branch format: ${DRONE_COMMIT_BRANCH}"
        exit 1
    fi
    VERSION_FOLDER="$(echo ${DRONE_COMMIT_BRANCH} | tr / -)"
    echo "---- VERSION_FOLDER: ${VERSION_FOLDER}"
    if [[ -z "${VERSION_FOLDER}" ]]; then
        echo "ERROR: failed to get VERSION_FOLDER"
        exit 1
    fi
fi

echo "---- Downloading ossutil"
wget -O /bin/ossutil "https://gosspublic.alicdn.com/ossutil/${OSSUTIL_VERSION}/ossutil32"
chmod 755 /bin/ossutil

echo "---- Configuring ossutil"
ossutil config -e "${ALIYUN_ENDPOINT}" -i "${ALIYUN_ACCESS_KEY_ID}" -k "${ALIYUN_SECRET_ACCESS_KEY}"

echo "---- Removing existing asset files"
ossutil rm -rf "${ALIYUN_BUCKET}/${VERSION_FOLDER}/"

echo "---- Creating folders"
ossutil mkdir "${ALIYUN_BUCKET}/${VERSION_FOLDER}/assets" || echo "---- assets folder already exists" # Recreate the folder just deleted
ossutil mkdir "${ALIYUN_BUCKET}/${LOGO_FOLDER}/" || echo "---- logo folder already exists" # Ensure LOGO folder exists

echo "---- Copy asset files"
ossutil cp -rf "./assets" "${ALIYUN_BUCKET}/${VERSION_FOLDER}/assets/"
ossutil cp -f "./index.yaml" "${ALIYUN_BUCKET}/${VERSION_FOLDER}/"

echo "---- Copy LOGO files"
ossutil cp -rf "./assets/logo" "${ALIYUN_BUCKET}/${LOGO_FOLDER}/"

echo '---- Set ACL for file'
ossutil set-acl ${ALIYUN_BUCKET}/${VERSION_FOLDER} ${VERSION_FOLDER_ACCESS} -rf
ossutil set-acl ${ALIYUN_BUCKET}/${LOGO_FOLDER} ${LOGO_FOLDER_ACCESS} -rf
