image:
  repository: "docker.io/cnrancher/webhook-receiver"
  tag: v0.1.5

port: 9094
replicas: 1

service:
  type: NodePort
  nodePort: 30030

config:

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: {}

affinity: {}
