apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  config.yml: |-
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: true
