apiVersion: v2
appVersion: 0.2.0
description: A Helm chart for HAMi DRA
home: https://github.com/Project-HAMi/HAMi-DRA
keywords:
- webhook
- kubernetes
- admission-controller
- hami
- dra
maintainers:
- name: hami-dra
  url: https://github.com/Project-HAMi/HAMi-DRA
name: hami-dra
sources:
- https://github.com/Project-HAMi/HAMi-DRA
type: application
version: 0.2.0
