apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-scheduler-policy
  namespace: {{ .Release.Namespace }}
data:
 policy.cfg : |
  {
    "kind" : "Policy",
    "apiVersion" : "v1",
    "extenders" : [{
      "urlPrefix": "http://localhost:{{ .Values.scheduler.port }}",
      "filterVerb": "filter",
      "prioritizeVerb": "",
      "preemptVerb": "",
      "bindVerb": "",
      "weight": 1,
      "managedResources": [
        {
          "name": "{{ .Values.resources.name }}",
          "ignoredByScheduler": false
        }
      ],
      "enableHttps": false
    }]
  }