apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-{{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
      component: ui
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        component: ui
    spec:
      containers:
        - name: ui
          image: "{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: API_TOKEN
            value: "{{ .Values.apiToken }}"
          - name: SERVER_URL
            value: "{{ .Values.serverUrl }}"
          - name: THANOS_URL
            value: "http://access-thanos/global-monitoring/v2"
          {{- if .Values.title }}
          - name: CUSTOM_RANCHER_TITLE
            value: {{ .Values.title }}
          {{- end }}
          {{- if .Values.tabTitle }}
          - name: CUSTOM_RANCHER_TAB_TITLE
            value: {{ .Values.tabTitle }}
          {{- end }}
          {{- if .Values.favicon }}
          - name: CUSTOM_RANCHER_FAVICON
            value: {{ .Values.favicon }}
          {{- end }}
          {{- if .Values.logo }}
          - name: CUSTOM_RANCHER_LOGO
            value: {{ .Values.logo }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
      {{- include "linux-node-selector" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- include "linux-node-tolerations" . | nindent 8 }}
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
