global:
  cattle:
    systemDefaultRegistry: ""

ackOperator:
  image:
    repository: cnrancher/ack-operator
    tag: v2.14.1-ent-rc2

httpProxy: ""
httpsProxy: ""
noProxy: ""
additionalTrustedCAs: false
leaderElect: true
lockName: ""
lockNamespace: ""
qps: ""
burst: ""
