apiVersion: v1
kind: Service
metadata:
  labels:
    app: gpu-dcgm-exporter
    monitoring.coreos.com: "true"
  name: expose-gpu-dcgm-metrics
  namespace: cattle-prometheus
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.ports.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.ports.metrics.port }}
  selector:
    app: gpu-dcgm-exporter
  type: ClusterIP
