apiVersion: v1
appVersion: 1.7.2
description: NGINX Ingress Controller
icon: https://pandaria-catalog.oss-cn-hangzhou.aliyuncs.com/assets/logo/f5-nginx-ingress.png
keywords:
- ingress
- nginx
maintainers:
- email: xuefeng@rancher.com
  name: xuefeng.yin
name: nginx-ingress
sources:
- https://github.com/nginxinc/kubernetes-ingress/tree/v1.7.2/deployments/helm-chart
version: 1.7.2
