{{- if eq .Values.global.installationType "submariner" }}
apiVersion: submariner.io/v1alpha1
kind: Submariner
metadata:
  name: submariner
  namespace: {{ .Release.Namespace }}
spec:
  broker: k8s
  brokerK8sApiServer: {{ .Values.broker.server }}
  brokerK8sApiServerToken: {{ .Values.broker.token }}
  brokerK8sCA: {{ .Values.broker.ca }}
  brokerK8sRemoteNamespace: {{ .Values.broker.namespace }}
  brokerK8sInsecure: {{ .Values.broker.insecure }}
  ceIPSecDebug: {{ .Values.ipsec.debug }}
  ceIPSecForceUDPEncaps: {{ .Values.ipsec.forceUDPEncaps }}
  ceIPSecIKEPort: {{ .Values.ipsec.ikePort }}
  ceIPSecNATTPort: {{ .Values.ipsec.natPort }}
  ceIPSecPSK: {{ .Values.ipsec.psk }}
  clusterCIDR: "{{ .Values.submariner.clusterCidr }}"
  clusterID: {{ .Values.submariner.clusterId }}
  colorCodes: {{ .Values.submariner.colorCodes }}
  debug: {{ .Values.submariner.debug }}
  loadBalancerEnabled: {{ .Values.submariner.loadBalancerEnabled }}
  namespace: {{ .Release.Namespace }}
  airGappedDeployment: {{ .Values.submariner.airGappedDeployment }}
  natEnabled: {{ .Values.submariner.natEnabled }}
  repository: {{ template "system_default_registry" . }}{{ .Values.submariner.images.repository }}
  version: {{ default .Chart.AppVersion .Values.submariner.images.tag }}
{{- with .Values.images }}
{{- if . }}
  imageOverrides:
    {{- if index . "submariner-operator" }}
    submariner-operator: {{ template "system_default_registry" $ }}{{ (index . "submariner-operator").repository }}:{{ (index . "submariner-operator").tag }}
    {{- end }}
    {{- if index . "submariner-gateway" }}
    submariner-gateway: {{ template "system_default_registry" $ }}{{ (index . "submariner-gateway").repository }}:{{ (index . "submariner-gateway").tag }}
    {{- end }}
    {{- if index . "submariner-route-agent" }}
    submariner-routeagent: {{ template "system_default_registry" $ }}{{ (index . "submariner-route-agent").repository }}:{{ (index . "submariner-route-agent").tag }}
    {{- end }}
    {{- if index . "submariner-globalnet" }}
    submariner-globalnet: {{ template "system_default_registry" $ }}{{ (index . "submariner-globalnet").repository }}:{{ (index . "submariner-globalnet").tag }}
    {{- end }}
    {{- if index . "submariner-networkplugin-syncer" }}
    submariner-networkplugin-syncer: {{ template "system_default_registry" $ }}{{ (index . "submariner-networkplugin-syncer").repository }}:{{ (index . "submariner-networkplugin-syncer").tag }}
    {{- end }}
    {{- if index . "lighthouse-agent" }}
    submariner-lighthouse-agent: {{ template "system_default_registry" $ }}{{ (index . "lighthouse-agent").repository }}:{{ (index . "lighthouse-agent").tag }}
    {{- end }}
    {{- if index . "lighthouse-coredns" }}
    submariner-lighthouse-coredns: {{ template "system_default_registry" $ }}{{ (index . "lighthouse-coredns").repository }}:{{ (index . "lighthouse-coredns").tag }}
    {{- end }}
    {{- if index . "submariner-nettest" }}
    submariner-nettest: {{ template "system_default_registry" $ }}{{ (index . "submariner-nettest").repository }}:{{ (index . "submariner-nettest").tag }}
    submariner-metrics-proxy: {{ template "system_default_registry" $ }}{{ (index . "submariner-nettest").repository }}:{{ (index . "submariner-nettest").tag }}
    {{- end }}
{{- end }}
{{- end }}
  serviceCIDR: "{{ .Values.submariner.serviceCidr }}"
  globalCIDR: "{{ .Values.submariner.globalCidr }}"
  clustersetIPCIDR: "{{ .Values.submariner.clustersetIpCidr }}"
  clustersetIPEnabled: {{ .Values.submariner.clustersetIpEnabled }}
  serviceDiscoveryEnabled: {{ .Values.submariner.serviceDiscovery }}
  cableDriver: {{ .Values.submariner.cableDriver }}
  connectionHealthCheck:
    enabled: {{ .Values.submariner.healthcheckEnabled }}
    intervalSeconds: 1
    maxPacketLossCount: 5
{{- with .Values.submariner.coreDNSCustomConfig }}
  coreDNSCustomConfig:
    configMapName: {{ .configMapName }}
    namespace: {{ .namespace }}
{{- end }}
{{- end }}
