apiVersion: v1
version: 2.0.1
name: xsky
appVersion: 2.0.1
# kubeVersion: 1.13.0
description: "Container Storage Interface (CSI) driver, provisioner, snapshotter, and attacher for XSKY block"
icon: https://www.xsky.com/wp-content/themes/xsky/assets/imgs/logo.png
home: https://www.xsky.com
keywords:
  - xsky
  - block-storage
  - iSCSI
  - storage
maintainers:
  - name: zhucan
    email: zhucan@xsky.com
