name: OSS Sync Helm

on:
  push:
    branches:
      - 'release/*'
      - 'dev/*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref_name}}
    - name: Upload Helm Repo
      if: ${{ github.repository == 'cnrancher/pandaria-catalog' }}
      env:
        ALIYUN_BUCKET: oss://pandaria-catalog
        ALIYUN_ENDPOINT: https://oss-cn-hangzhou.aliyuncs.com/
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
        ALIYUN_SECURITY_TOKEN: ""
        VERSION_FOLDER_ACCESS: public-read
        LOGO_FOLDER_ACCESS: public-read
        OSSUTIL_VERSION: "1.7.19"
        LOGO_FOLDER: assets/logo
      run: |
        scripts/aliyun-oss-sync
