apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: ackclusterconfigs.ack.pandaria.io
spec:
  group: ack.pandaria.io
  names:
    kind: ACKClusterConfig
    plural: ackclusterconfigs
    shortNames:
      - ackcc
    singular: ackclusterconfig
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                aliyun_credential_secret:
                  nullable: true
                  type: string
                cloudMonitorFlags:
                  type: boolean
                cluster_id:
                  nullable: true
                  type: string
                clusterIsUpgrading:
                  type: boolean
                clusterType:
                  nullable: true
                  type: string
                containerCidr:
                  nullable: true
                  type: string
                disableRollback:
                  type: boolean
                endpointPublicAccess:
                  type: boolean
                imported:
                  type: boolean
                keyPair:
                  nullable: true
                  type: string
                kubernetesVersion:
                  nullable: true
                  type: string
                loginPassword:
                  nullable: true
                  type: string
                masterAutoRenew:
                  type: boolean
                masterAutoRenewPeriod:
                  type: integer
                masterCount:
                  type: integer
                masterInstanceChargeType:
                  nullable: true
                  type: string
                masterInstanceTypes:
                  items:
                    nullable: true
                    type: string
                  nullable: true
                  type: array
                masterPeriod:
                  type: integer
                masterPeriodUnit:
                  nullable: true
                  type: string
                masterSystemDiskCategory:
                  nullable: true
                  type: string
                masterSystemDiskSize:
                  type: integer
                masterVswitchIds:
                  items:
                    nullable: true
                    type: string
                  nullable: true
                  type: array
                name:
                  nullable: true
                  type: string
                node_pool_list:
                  items:
                    properties:
                      auto_renew:
                        type: boolean
                      auto_renew_period:
                        type: integer
                      data_disk:
                        items:
                          properties:
                            auto_snapshot_policy_id:
                              nullable: true
                              type: string
                            category:
                              nullable: true
                              type: string
                            encrypted:
                              nullable: true
                              type: string
                            size:
                              type: integer
                          type: object
                        nullable: true
                        type: array
                      eip_bandwidth:
                        type: integer
                      eip_internet_charge_type:
                        nullable: true
                        type: string
                      instance_charge_type:
                        nullable: true
                        type: string
                      instance_types:
                        items:
                          nullable: true
                          type: string
                        nullable: true
                        type: array
                      instances_num:
                        type: integer
                      is_bond_eip:
                        type: boolean
                      key_pair:
                        nullable: true
                        type: string
                      login_password:
                        nullable: true
                        type: string
                      name:
                        nullable: true
                        type: string
                      nodepool_id:
                        nullable: true
                        type: string
                      period:
                        type: integer
                      period_unit:
                        nullable: true
                        type: string
                      platform:
                        nullable: true
                        type: string
                      scaling_type:
                        nullable: true
                        type: string
                      system_disk_category:
                        nullable: true
                        type: string
                      system_disk_size:
                        type: integer
                      v_switch_ids:
                        items:
                          nullable: true
                          type: string
                        nullable: true
                        type: array
                    type: object
                  nullable: true
                  type: array
                nodeCidrMask:
                  type: integer
                osType:
                  nullable: true
                  type: string
                pauseClusterUpgrade:
                  type: boolean
                platform:
                  nullable: true
                  type: string
                proxyMode:
                  nullable: true
                  type: string
                regionId:
                  nullable: true
                  type: string
                resourceGroupId:
                  nullable: true
                  type: string
                securityGroupId:
                  nullable: true
                  type: string
                serviceCidr:
                  nullable: true
                  type: string
                snatEntry:
                  type: boolean
                sshFlags:
                  type: boolean
                timeoutMins:
                  type: integer
                vpcId:
                  nullable: true
                  type: string
                vswitchIds:
                  items:
                    nullable: true
                    type: string
                  nullable: true
                  type: array
              type: object
            status:
              properties:
                failureMessage:
                  nullable: true
                  type: string
                phase:
                  nullable: true
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
